export const LOYALTY_BODY_COPY =
  "LOYALTY PERKS IS OUR WAY OF GIVING BACK TO OUR SIDEOUT FOLKS EARN A POINT FOR EVERY DRINK PURCHASE AND ENJOY REWARDS ALONG THE WAY. ONE PERSONAL DRINK IS EQUALS ONE POINT.";
